// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByBZ6JWUr1NZci9TZFG_OT0-pyq56VIbw',
    appId: '1:50065896162:web:67ccc87527a5422e9e64bb',
    messagingSenderId: '50065896162',
    projectId: 'hearth-9e897',
    authDomain: 'hearth-9e897.firebaseapp.com',
    storageBucket: 'hearth-9e897.firebasestorage.app',
    measurementId: 'G-G902QTBD6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_f8PxaCyE84YsaaMXzhzn1-51dxFLwWY',
    appId: '1:50065896162:android:0f996c7d5a5014709e64bb',
    messagingSenderId: '50065896162',
    projectId: 'hearth-9e897',
    storageBucket: 'hearth-9e897.firebasestorage.app',
  );

}